name: CI
on: [push]

jobs:
  build:
    runs-on: self-hosted
    if: contains(github.event.head_commit.message, '[build]')
    env:
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
      BUILD_ENGINE: ${{ secrets.BUILD_ENGINE }}
      EDM_DATA: ${{ secrets.EDM_DATA }} 
    steps:
    - uses: actions/checkout@v2
    - name: dataloading ...
      working-directory: colp_build
      shell: bash
      run: ./01_dataloading.sh
    - name: install update ...
      run: |
        sudo apt update
        sudo apt install -y postgresql-client-common
    - name: run build ...
      working-directory: colp_build
      run: ./02_build.sh
