name: CI
on: [push]

jobs:
  skip:
    name: Build and test
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[build]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"
  build:
    needs: skip
    runs-on: ubuntu-latest
    env:
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
      BUILD_ENGINE: ${{ secrets.BUILD_ENGINE }}
    steps:
    - uses: actions/checkout@v2
    - name: dataloading ...
      working-directory: colp_build
      shell: bash
      run: ./01_dataloading.sh
    - name: install update ...
      run: |
        sudo apt update
        sudo apt install -y postgresql-client-common
    - name: run build ...
      working-directory: colp_build
      run: ./02_build.sh
