name: CI
on: [push]

jobs:
  build:
    runs-on: self-hosted
    if: contains(github.event.head_commit.message, '[build]')
    env:
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
      BUILD_ENGINE: ${{ secrets.BUILD_ENGINE }}
      EDM_DATA: ${{ secrets.EDM_DATA }}
      AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies ...
      run: |
        sudo apt update
        sudo apt install -y postgresql-client-common
        curl -O https://dl.min.io/client/mc/release/linux-amd64/archive/mc.RELEASE.2020-06-26T19-56-55Z
        mv mc.RELEASE.2020-06-26T19-56-55Z mc
        sudo chmod +x mc
        sudo mv ./mc /usr/bin/ 
        mc config host add spaces $AWS_S3_ENDPOINT $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY --api S3v4
    - name: Dataloading ...
      working-directory: colp_build
      shell: bash
      run: ./01_dataloading.sh
    - name: Build COLP ...
      working-directory: colp_build
      run: ./02_build.sh
    - name: Create exports and upload to s3 ...
      working-directory: colp_build
      run: ./03_export.sh
