name: CI
on: [push]

jobs:
  build:
    runs-on: self-hosted
    if: contains(github.event.head_commit.message, '[build]')
    env:
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
      BUILD_ENGINE: ${{ secrets.BUILD_ENGINE }}
      EDM_DATA: ${{ secrets.EDM_DATA }}
      AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
    steps:
    - uses: actions/checkout@v2
    - name: Dataloading ...
      working-directory: colp_build
      shell: bash
      run: ./01_dataloading.sh
    - name: Install updates ...
      run: |
        sudo apt update
        sudo apt install -y postgresql-client-common
    - name: Build COLP ...
      working-directory: colp_build
      run: ./02_build.sh
    - name: Create exports and upload to s3 ...
      working-directory: colp_build
      run: ./03_export.sh
