name: test
on: [push]

jobs:
  skip:
    name: Build and test
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[build]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"
  build:
    needs: skip
    runs-on: ubuntu-latest
    env:
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
      BUILD_ENGINE: postgresql://postgres@localhost:5432/postgres
    services:
      postgis:
        image: mdillon/postgis:latest
        ports: 
          - 5432:5432 
    steps:
    - uses: actions/checkout@v2
    - name: dataloading ...
      working-directory: colp_build
      shell: bash
      run: |
        docker run --rm\
            -v `pwd`:/home/colp_build\
            -w /home/colp_build\
            -e RECIPE_ENGINE=$RECIPE_ENGINE\
            -e BUILD_ENGINE=$BUILD_ENGINE\
            sptkl/cook:latest bash -c "python3 python/dataloading.py"
        docker run --rm\
            -v `pwd`:/home/colp_build\
            -w /home/colp_build\
            -e RECIPE_ENGINE=$RECIPE_ENGINE\
            -e BUILD_ENGINE=$BUILD_ENGINE\
            sptkl/docker-geosupport:latest bash -c "python3 python/geocode.py"
